# Generated by Django 4.2.3 on 2023-09-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Walks_Service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walk',
            name='poopScore',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='walk',
            name='reactivityScore',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='walk',
            name='sensitivityScore',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
