# Generated by Django 4.2.3 on 2023-09-14 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dogs_Service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='sponsorExpirationDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
